apiVersion: v1 
kind: Pod 
metadata: 
  name: apache
  namespace: default 
spec: 
  containers: 
  - name: apache
    image: bitnami/apache:latest
    ports: 
      - containerPort: 80 
    env: 
      - name: TOP_SECRET 
        valueFrom: 
          secretKeyRef: 
            name: top-secret 
            key: topsecret
